version: "3.9"
services:
    frontend:
        image: joanna14/frontend:v2
        networks:
            - back-front
        depends_on:
            - backend
        ports:
            - "3000:3000"
        deploy:
            replicas: 2
            placement:
                max_replicas_per_node: 1
    backend:
        image: joanna14/backend:v2
        ports:
            - "5002:5002"     
        deploy:
            replicas: 2
            placement:
                max_replicas_per_node: 1
            update_config:
                order: start-first
            rollback_config:
                order: stop-first    
        depends_on:
            - db
        networks:
            - back-db
            - back-front

    db:
        image: postgres:12
        environment:
            POSTGRES_DB: ShelterHelperDb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
        volumes:
            - db-volume:/var/lib/postgresql/data
        networks:
            - back-db
            - admin-db

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - admin-db
        depends_on:
            - db


networks:
    back-db:
    back-front:
    admin-db:

volumes:
    db-volume: