version: "3.9"
services:
    frontend:
        image: joanna14/frontend:v3
        depends_on:
            - backend
        ports:
            - "3000:3000"
        networks:
            - logging
        deploy:
            replicas: 1
            placement:
                max_replicas_per_node: 1
    backend:
        image: joanna14/backend:v3
        ports:
            - "5002:5002"     
        deploy:
            replicas: 1
            placement:
                max_replicas_per_node: 1
            update_config:
                order: start-first
            rollback_config:
                order: stop-first    
        depends_on:
            - db
        networks:
            - back-db
            - back-front
            - logging

    db:
        image: postgres:12
        environment:
            POSTGRES_DB: ShelterHelperDb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
        volumes:
            - db-volume:/var/lib/postgresql/data
        networks:
            - back-db
            - admin-db

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - admin-db
        depends_on:
            - db

    grafana:
      image: grafana/grafana:latest
      environment:
        GF_SERVER_HTTP_PORT: 3001
      volumes:
        - grafana-volume:/var/lib/grafana
      ports:
        - 3001:3001
      networks:
        - logging
    
    prometheus:
      image: prom/prometheus
      volumes:
        - ./prometheus/prom.yml:/etc/prometheus/prometheus.yml
      ports:
        - 9090:9090
      networks:
        - logging

networks:
    back-db:
    back-front:
    admin-db:
    logging:

volumes:
    db-volume:
    grafana-volume:
