version: "3.9"
services:
    frontend:
        image: joanna14/frontend:v3
        depends_on:
            - backend
        ports:
            - "3000:3000"
    backend:
        image: joanna14/backend:v3
        ports:
            - "5002:5002"
        logging:
            driver: loki
            options:
                loki-url: http://host.docker.internal:3100/loki/api/v1/push       
        networks:
            - back-db
            - back-front
            - logging

    db:
        image: postgres:12
        environment:
            POSTGRES_DB: ShelterHelperDb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
        volumes:
            - db-volume:/var/lib/postgresql/data
        networks:
            - back-db
            - admin-db

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - admin-db
        depends_on:
            - db

    loki:
        image: grafana/loki
        volumes:
            - ./loki/loki.yml:/etc/config/loki.yml
            - ./loki/wal:/wal
        entrypoint:
            - /usr/bin/loki
            - -config.file=/etc/config/loki.yml
        ports:
            - 3100:3100
        networks:
            - logging
            - visualizing

    grafana:
        image: grafana/grafana
        volumes:
            - grafana-volume:/var/lib/grafana
        ports:
            - 3001:3001
        depends_on:
            - loki
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - visualizing

networks:
    back-db:
    back-front:
    admin-db:
    visualizing:
    logging:

volumes:
    db-volume:
    grafana-volume: