version: "3.9"
services:
    frontend:
        build: ./Frontend
        networks:
            - back-front
        depends_on:
            - backend
        ports:
            - "3000:3000"

    backend:
        build: ./Backend
        ports:
            - "7002:7002"
        depends_on:
            - db
        networks:
            - back-db
            - back-front

    db:
        image: postgres:12
        environment:
            POSTGRES_DB: ShelterHelperDb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin

        networks:
            - back-db

networks:
    back-db:
    back-front: