// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using ShelterHelper.Infrastructure.Data;

#pragma warning disable 219, 612, 618
#nullable enable

namespace ShelterHelper.Api.ShelterHelper.Infrastructure.Data.CompiledModels
{
    [DbContext(typeof(ShelterHelperContext))]
    public partial class ShelterHelperContextModel : RuntimeModel
    {
        static ShelterHelperContextModel()
        {
            var model = new ShelterHelperContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static ShelterHelperContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
