// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace ShelterHelper.Api.ShelterHelper.Infrastructure.Data.CompiledModels
{
    public partial class ShelterHelperContextModel
    {
        partial void Initialize()
        {
            var bookings = BookingsEntityType.Create(this);
            var shelters = SheltersEntityType.Create(this);
            var users = UsersEntityType.Create(this);

            BookingsEntityType.CreateForeignKey1(bookings, shelters);
            BookingsEntityType.CreateForeignKey2(bookings, users);

            BookingsEntityType.CreateAnnotations(bookings);
            SheltersEntityType.CreateAnnotations(shelters);
            UsersEntityType.CreateAnnotations(users);

            AddAnnotation("ProductVersion", "6.0.5");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
